# Cloudflare Pages configuration for Proliferaite Website

name = "proliferaite-website"

# Use root directory as the build output (where our website files are located)
pages_build_output_dir = "."

# No build command needed for static files
# build = ""

# Compatibility settings for Pages
compatibility_date = "2023-05-18"

# Environment variables (if needed)
[env.production]
[env.production.vars]

[env.preview]
[env.preview.vars] 