# Cloudflare Pages configuration for Proliferaite Website

name = "proliferaite-website"

# Use root directory as the build output (where our website files are located)
pages_build_output_dir = "."

# No build command needed for static files
# build = ""

# Compatibility settings for Pages
compatibility_date = "2023-05-18"

# Environment variables (if needed)
[env.production]
[env.production.vars]

[env.preview]
[env.preview.vars]

# URL rewrites for clean URLs (serve .html files for extensionless URLs)
[[redirects]]
from = "/about"
to = "/about.html"
status = 200

[[redirects]]
from = "/our-story"
to = "/our-story.html"
status = 200

[[redirects]]
from = "/contact"
to = "/contact.html"
status = 200

[[redirects]]
from = "/terms"
to = "/terms.html"
status = 200

[[redirects]]
from = "/privacy-policy"
to = "/privacy-policy.html"
status = 200 